# Generated by Django 4.2.2 on 2023-06-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='概念板块代码')),
                ('name', models.CharField(max_length=8, verbose_name='概念板块名称')),
            ],
            options={
                'db_table': 'concepts',
            },
        ),
        migrations.CreateModel(
            name='ConceptStretagy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='股票名称')),
                ('code', models.CharField(max_length=16, verbose_name='股票代码')),
                ('concept', models.CharField(max_length=32, verbose_name='概念')),
                ('last_price', models.FloatField(verbose_name='最新价')),
                ('increase', models.CharField(max_length=8, verbose_name='近1周涨幅')),
            ],
            options={
                'db_table': 'conceptstretagy',
            },
        ),
        migrations.CreateModel(
            name='HotStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=8, verbose_name='股票名')),
                ('Rank', models.SmallIntegerField(verbose_name='排名')),
                ('Change', models.SmallIntegerField(verbose_name='排名变化')),
                ('Concept', models.CharField(max_length=32, verbose_name='概念')),
                ('Popularity', models.FloatField(verbose_name='人气')),
                ('Express', models.CharField(max_length=16, null=True, verbose_name='表现')),
                ('Time', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'db_table': 'hotstocks',
            },
        ),
        migrations.CreateModel(
            name='LimitupStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=8, verbose_name='股票名')),
                ('Code', models.CharField(max_length=8, verbose_name='股票代码')),
                ('Latest', models.FloatField(verbose_name='涨停价')),
                ('Currency_value', models.IntegerField(verbose_name='流通值')),
                ('Reason_type', models.CharField(max_length=32, verbose_name='涨停原因')),
                ('Limitup_type', models.CharField(max_length=8, verbose_name='涨停形态')),
                ('High_days', models.CharField(max_length=8, null=True, verbose_name='几天几板')),
                ('Change_rate', models.CharField(max_length=8, verbose_name='换手率')),
                ('Date', models.DateTimeField(auto_now=True, verbose_name='日期')),
            ],
            options={
                'db_table': 'limitupstocks',
            },
        ),
        migrations.CreateModel(
            name='Securities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='股票代码')),
                ('value', models.CharField(max_length=8, verbose_name='中文名称')),
            ],
            options={
                'db_table': 'securities',
            },
        ),
    ]
