# Generated by Django 4.2.2 on 2023-07-02 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='概念板块代码')),
                ('name', models.CharField(max_length=8, verbose_name='概念板块名称')),
            ],
            options={
                'db_table': 'concept',
            },
        ),
        migrations.CreateModel(
            name='ConceptStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='股票名称')),
                ('code', models.CharField(max_length=16, verbose_name='股票代码')),
                ('concept', models.CharField(max_length=32, verbose_name='概念')),
                ('latest', models.FloatField(verbose_name='最新价')),
                ('weekly_increase', models.CharField(max_length=8, verbose_name='近1周涨幅')),
            ],
            options={
                'db_table': 'conceptstock',
            },
        ),
        migrations.CreateModel(
            name='HotStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='股票名')),
                ('rank', models.SmallIntegerField(verbose_name='排名')),
                ('change', models.SmallIntegerField(verbose_name='排名变化')),
                ('concept', models.CharField(max_length=32, verbose_name='概念')),
                ('popularity', models.FloatField(verbose_name='人气')),
                ('express', models.CharField(max_length=16, null=True, verbose_name='表现')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'db_table': 'hotstock',
            },
        ),
        migrations.CreateModel(
            name='LimitupStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='股票代码')),
                ('name', models.CharField(max_length=8, verbose_name='股票名')),
                ('latest', models.FloatField(verbose_name='涨停价')),
                ('currency_value', models.FloatField(verbose_name='流通市值')),
                ('reason_type', models.CharField(max_length=128, null=True, verbose_name='涨停原因')),
                ('limit_up_type', models.CharField(max_length=8, verbose_name='涨停形态')),
                ('high_days', models.CharField(max_length=8, null=True, verbose_name='几天几板')),
                ('change_rate', models.FloatField(null=True, verbose_name='换手率')),
                ('change_tag', models.CharField(max_length=32, null=True, verbose_name='换手形态')),
                ('first_limit_up_time', models.CharField(max_length=32, null=True)),
                ('last_limit_up_time', models.CharField(max_length=32, null=True)),
                ('is_new', models.IntegerField(null=True)),
                ('is_again_limit', models.IntegerField(null=True, verbose_name='封板次数')),
                ('order_amount', models.FloatField(null=True, verbose_name='封单额')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
            ],
            options={
                'db_table': 'limitupstock',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='股票代码')),
                ('srcSecurityCode', models.CharField(max_length=16, verbose_name='证券代码')),
                ('value', models.CharField(max_length=8, verbose_name='中文名称')),
                ('latest', models.FloatField(null=True)),
                ('currency_value', models.FloatField(null=True)),
                ('sixty_days_increase', models.FloatField(null=True)),
                ('year_increase', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'security',
            },
        ),
        migrations.CreateModel(
            name='StockRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srcSecurityCode', models.CharField(max_length=16)),
                ('rank', models.TextField(default='null', null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
            ],
            options={
                'db_table': 'stockrank',
            },
        ),
    ]
