# Generated by Django 4.2.2 on 2023-07-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_stockzy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitupstock',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
