# Generated by Django 4.2.2 on 2023-07-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_limitupstock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitupstock',
            name='date',
            field=models.DateField(),
        ),
    ]
