# Generated by Django 4.0.6 on 2023-07-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_limitupstock_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitupstock',
            name='time_preview',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
