# Generated by Django 4.0.6 on 2023-08-05 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_limitupstock_time_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRealtimeRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srcSecurityCode', models.CharField(max_length=16)),
                ('rank', models.IntegerField(default='null', null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'stockrealtimeRank',
            },
        ),
    ]
