# Generated by Django 4.0.6 on 2023-08-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_stockrealtimerank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockRank',
        ),
        migrations.AlterField(
            model_name='stockrealtimerank',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
