# Generated by Django 4.0.6 on 2023-08-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_delete_stockrank_alter_stockrealtimerank_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockrealtimerank',
            table='stockrealtimerank',
        ),
    ]
