# Generated by Django 4.0.6 on 2023-08-20 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_stockrealtimerank_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=8, verbose_name='股票名称')),
                ('latest', models.FloatField(null=True, verbose_name='最新价')),
                ('currency_value', models.FloatField(verbose_name='流通市值')),
                ('increase', models.FloatField(null=True)),
                ('acceleration', models.FloatField(null=True, verbose_name='涨速')),
                ('sixty_days_increase', models.FloatField(null=True)),
                ('year_increase', models.FloatField(null=True)),
                ('time_increase', models.TextField(blank=True, default='[]')),
                ('time_volume', models.TextField(blank=True, default='[]')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
            ],
            options={
                'db_table': 'bidprice',
            },
        ),
    ]
