# Generated by Django 4.0.6 on 2023-08-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_bidprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidprice',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterField(
            model_name='bidprice',
            name='date',
            field=models.DateField(),
        ),
    ]
